package com.halovoid.lncrawler.data.artifact.generators

import com.halovoid.lncrawler.data.artifact.ArtifactGenerator
import com.halovoid.lncrawler.data.repository.StorageRepository
import com.halovoid.lncrawler.data.scheduler.RequestMetadata
import com.halovoid.lncrawler.domain.models.Chapter
import com.halovoid.lncrawler.domain.models.Novel
import com.halovoid.lncrawler.domain.models.Volume
import android.net.Uri
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.util.zip.CRC32
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream
import kotlin.math.abs

private data class EpubItem(
    val fileName: String,
    val content: ByteArray,
    val mediaType: String,
    val id: String
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as EpubItem

        if (fileName != other.fileName) return false
        if (!content.contentEquals(other.content)) return false
        if (mediaType != other.mediaType) return false
        if (id != other.id) return false

        return true
    }

    override fun hashCode(): Int {
        var result = fileName.hashCode()
        result = 31 * result + content.contentHashCode()
        result = 31 * result + mediaType.hashCode()
        result = 31 * result + id.hashCode()
        return result
    }
}

class EpubGenerator(
    private val storageRepository: StorageRepository
) : ArtifactGenerator {
    override val format: String = "EPUB"

    // Constants and CSS for EPUB
    private companion object {
        const val styleFileName = "style.css"
        const val projectUrl = "https://github.com/Binit06/LNCrawler"

        val epubStyleCSS = """
            |body { font-family: sans-serif; padding: 1em; line-height: 1.5; }
            |h1 { text-align: center; margin-top: 2em; }
            |h3 { text-align: center; font-weight: normal; }
            |.synopsis { margin-top: 2em; font-style: italic; }
            |.footer { margin-top: 4em; font-size: 0.8em; border-top: 1px solid #ccc; padding-top: 1em; }
            |#volume h1 { margin-top: 40%; font-size: 3em; text-align: center; }
            |#chapter h4 { opacity: 0.75; margin-bottom: 0; }
            |img { max-width: 100%; height: auto; }
        """.trimMargin()
    }

    // XHTML Wrapper
    private fun wrapXHTML(title: String, body: String): String {
        return """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!DOCTYPE html>
            |<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
            |<head>
            |    <meta charset="UTF-8" />
            |    <title>$title</title>
            |    <link rel="stylesheet" href="$styleFileName" type="text/css"/>
            |</head>
            |<body>
            |    $body
            |</body>
            |</html>
        """.trimMargin()
    }

    // Page Templates
    private fun buildIntroPage(novel: Novel): String {
        val content = """
            |<div id="intro">
            |    <h1>${novel.title}</h1>
            |    <h3>${novel.author ?: "Unknown Author"}</h3>
            |    <div class="synopsis">
            |        ${novel.description ?: ""}
            |    </div>
            |    <div class="footer">
            |        <b>Source:</b> <a href="${novel.url}">${novel.url}</a>
            |        <br/>
            |        <i>Generated by <b>
            |        <a href="$projectUrl">LN Crawler</a></b></i>
            |    </div>
            |</div>
        """.trimMargin()
        return  wrapXHTML("Intro Page", content)
    }

    private fun buildVolumePage(volume: Volume): String {
        val content = """
            |<div id="volume">
            |    <h1>${"Volume ${volume.volumeIndex}"}</h1>
            |</div>
        """.trimMargin()
        return wrapXHTML("Volumes ${volume.volumeIndex}", content)
    }

    private fun buildChapterPage(chapter: Chapter, htmlContent: String): String {
        val displayTitle = chapter.title.ifBlank { "Chapter ${chapter.index}" }
        val content = """
            |<div id="chapter">
            |    <h4 aria-hidden="true">${chapter.index}</h4>
            |    <h1>${displayTitle}</h1>
            |    $htmlContent
            |</div>
        """.trimMargin()
        return wrapXHTML(displayTitle, content)
    }

    // Content to be written inside content.opf
    private fun generateContainerXML(): String {
        return """
            |<?xml version="1.0" encoding="UTF-8"?>
            |<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
            |    <rootfiles>
            |        <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
            |    </rootfiles>
            |</container>
        """.trimMargin()
    }

    private fun generateOpf(novel: Novel, items: List<EpubItem>): String {
        val manifest = items.joinToString("\n") {
            val navAttr = if (it.fileName == "nav.xhtml") " properties=\"nav\"" else ""
            "|      <item id=\"${it.id}\" href=\"${it.fileName}\" media-type=\"${it.mediaType}\"$navAttr/>"
        }

        // Determined reading order
        val spine = items.filter { it.mediaType == "application/xhtml+xml" }
            .joinToString("\n") { "|        <itemref idref=\"${it.id}\"/>" }

        return """
            |<?xml version="1.0" encoding="UTF-8"?>
            |<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="pub-id" version="3.0">
            |    <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
            |        <dc:identifier id="pub-id">${novel.url.hashCode()}</dc:identifier>
            |        <dc:title>${novel.title}</dc:title>
            |        <dc:creator>${novel.author ?: "Unknown"}</dc:creator>
            |        <dc:language>en</dc:language>
            |        <dc:description>${novel.description ?: ""}</dc:description>
            |        <meta property="dcterms:modified">${java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", java.util.Locale.US).apply { timeZone = java.util.TimeZone.getTimeZone("UTC") }.format(java.util.Date())}</meta>
            |    </metadata>
            |    <manifest>
            |        <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
            $manifest
            |    </manifest>
            |    <spine toc="ncx">
            $spine
            |    </spine>
            |</package>
        """.trimMargin()
    }

    private fun generateNcx(novel: Novel, items: List<EpubItem>): String {
        val navPoints = items.filter { it.mediaType == "application/xhtml+xml" }
            .mapIndexed { index, item ->
                """
                |<navPoint id="navPoint-${index + 1}" playOrder="${index + 1}">
                |    <navLabel><text>${item.id.replace("_", " ")}</text></navLabel>
                |    <content src="${item.fileName}"/>
                |</navPoint>
            """.trimMargin()
            }.joinToString("\n")

        return """
            |<?xml version="1.0" encoding="UTF-8"?>
            |<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
            |    <head>
            |        <meta name="dtb:uid" content="pub-${abs(novel.url.hashCode())}"/>
            |        <meta name="dtb:depth" content="1"/>
            |        <meta name="dtb:totalPageCount" content="0"/>
            |        <meta name="dtb:maxPageNumber" content="0"/>
            |    </head>
            |    <docTitle><text>${novel.title}</text></docTitle>
            |    <navMap>
            |        $navPoints
            |    </navMap>
            |</ncx>
        """.trimMargin()
    }

    private fun generateNav(novel: Novel, items: List<EpubItem>): String {
        val listItems = items.filter { it.mediaType == "application/xhtml+xml" }
            .joinToString("\n") {
                """<li><a href="${it.fileName}">${it.id.replace("_", " ")}</a></li>"""
            }
        val content = """
            |<nav xmlns:epub="http://www.idpf.org/2007/ops" epub:type="toc" id="toc">
            |    <h1>Table of Contents</h1>
            |    <ol>
            |        $listItems
            |    </ol>
            |</nav>
        """.trimMargin()
        return wrapXHTML("Table of Contents", content)
    }


    override suspend fun generate(
        novel: Novel,
        volumes: List<Volume>,
        chapters: List<Chapter>,
        metadata: RequestMetadata
    ): File = withContext(Dispatchers.IO) {
        val items = mutableListOf<EpubItem>()

        // 1. Add static assets
        items.add(EpubItem(styleFileName, epubStyleCSS.toByteArray(), "text/css", "style"))
        items.add(EpubItem("intro.xhtml", buildIntroPage(novel).toByteArray(), "application/xhtml+xml", "intro"))

        // 2. Build Chapters and Volumes
        // Group chapters by Volume to maintain the hierarchy
        volumes.sortedBy { it.volumeIndex }.forEach { volume ->
            items.add(EpubItem(
                "volume_${volume.volumeIndex}.xhtml",
                buildVolumePage(volume).toByteArray(),
                "application/xhtml+xml",
                "volume_${volume.volumeIndex}"
            ))

            chapters.filter { it.volumeId == volume.id }
                .sortedBy { it.index }
                .forEach { chapter ->
                    val content = chapter.fileLocation?.let { loc ->
                        storageRepository.readText(Uri.parse(loc))
                    } ?: "<p><em>Content not available</em></p>"

                    items.add(EpubItem(
                        "chapter_${chapter.index.toString().padStart(5, '0')}.xhtml",
                        buildChapterPage(chapter, content).toByteArray(),
                        "application/xhtml+xml",
                        "chapter_${chapter.index}"
                    ))
                }
        }

        // 3. Add Navigation
        items.add(EpubItem("nav.xhtml", generateNav(novel, items).toByteArray(), "application/xhtml+xml", "nav"))

        //4. Prepare Metadata Files
        val opf = generateOpf(novel, items)
        val ncx = generateNcx(novel, items)

        // Package into ZIP File
        val tempFile = File(storageRepository.getCacheDir(), "${novel.title.replace(" ", "_")}.epub")
        ZipOutputStream(FileOutputStream(tempFile)).use { zip ->

            val mimeBytes = "application/epub+zip".toByteArray()
            val mimeEntry = ZipEntry("mimetype").apply {
                method = ZipEntry.STORED
                size = mimeBytes.size.toLong()
                compressedSize = mimeBytes.size.toLong()
                crc = CRC32().apply { update(mimeBytes) }.value
            }
            zip.putNextEntry(mimeEntry)
            zip.write(mimeBytes)
            zip.closeEntry()

            zip.putNextEntry(ZipEntry("META-INF/container.xml"))
            zip.write(generateContainerXML().toByteArray())
            zip.closeEntry()

            zip.putNextEntry(ZipEntry("OEBPS/content.opf"))
            zip.write(opf.toByteArray())
            zip.closeEntry()

            zip.putNextEntry(ZipEntry("OEBPS/toc.ncx"))
            zip.write(ncx.toByteArray())
            zip.closeEntry()

            items.forEach { item ->
                zip.putNextEntry(ZipEntry("OEBPS/${item.fileName}"))
                zip.write(item.content)
                zip.closeEntry()
            }
        }

        tempFile
    }
}